Fork the lockdown test to reflect its also testing namespace overrides.
spiffe/helm-charts pull request #134
Opened 2023-03-17 21:22 UTC by kfox1111

A future patch set will change the lockdown test to drop out the namespace override test bits.

2023-03-17 21:31 UTC, marcofranssen requested changes
Could you add a temporary commit to run the tests? Also few nit-picky suggestions in there.

2023-03-17 21:31 UTC, marcofranssen commented on .github/tests/namespace-override/pre-install.sh
> +kubectl label namespace "spire-server" pod-security.kubernetes.io/enforce=restricted
```suggestion
kubectl create namespace spire-system
kubectl label namespace spire-system pod-security.kubernetes.io/enforce=privileged
kubectl create namespace spire-server
kubectl label namespace spire-server pod-security.kubernetes.io/enforce=restricted
```

2023-03-17 21:31 UTC, marcofranssen commented on .github/tests/namespace-override/post-install.sh
> +| spire-spiffe-oidc-discovery-provider | $("${k_wait[@]}" spire-server deployments.apps spire-spiffe-oidc-discovery-provider) |
```suggestion
| spire-server | $("${k_rollout_status[@]}" spire-server statefulset spire-server) |
| spire-spiffe-oidc-discovery-provider | $("${k_wait[@]}" spire-server deployments.apps spire-spiffe-oidc-discovery-provider) |
| spire-spiffe-csi-driver | $("${k_rollout_status[@]}" spire-system daemonset spire-spiffe-csi-driver) |
| spire-agent | $("${k_rollout_status[@]}" spire-system daemonset spire-agent) |
```

2023-03-17 22:06 UTC, kfox1111 commented on .github/tests/namespace-override/pre-install.sh
> +kubectl label namespace "spire-server" pod-security.kubernetes.io/enforce=restricted
Done

2023-03-17 22:29 UTC, kfox1111 commented
This is ready to go, but needs the version bump reverted. It was put in place to ensure all the changes work.

2023-03-21 14:34 UTC, marcofranssen commented on .github/tests/namespace-override/pre-install.sh
> +#!/bin/bash
```suggestion
#!/usr/bin/env bash

```

2023-03-21 14:41 UTC, marcofranssen commented on .github/tests/namespace-override/.env
> +export EXTRA_HELM_ARGS="--values=examples/production/values.yaml"
This should not be part of this test. I would expect just the namespace override.

2023-03-21 14:45 UTC, marcofranssen submitted a review, later dismissed
Can we rename this PR to just

`Replace lockdown test with namespace-override test`?

#127 replaces the lockdown test with just testing the production example (which is already locked down).

I even debate the value of testing these 2 namespace overrides. Feels a bit like this PR is obsolete when we merge #127

2023-03-21 14:57 UTC, kfox1111 commented
Trying to maintain history. the existing lockdown test is doing 2 things. testing production values, and namespace-override testing. To follow the established principal of one pr doing just one thing, we need to fork the test into the two so its obvious where the test came from. We then can continue to enhance both test separately in separate pr's.

2023-03-21 17:12 UTC, faisal-memon approved these changes

2023-03-21 17:14 UTC, merged