Ensure test overrides
spiffe/helm-charts pull request #186
Opened 2023-04-03 14:57 UTC by kfox1111

Some of the tests can't run on an isolated network. Make the images overridable.

2023-04-03 15:10 UTC, kfox1111 commented
Reworked https://github.com/spiffe/helm-charts/pull/155. It had some github issue that made us have to abandon it.

2023-05-23 15:32 UTC, marcofranssen commented on charts/spire/charts/tornjak-frontend/values.yaml
> +      tag: latest-20230517
```suggestion
      tag: 5.2.15
```

Found this tag via 

```bash
crane ls cgr.dev/chainguard/bash | grep -v latest | grep -v sbom | grep -v att | grep -v sig
```

2023-05-23 15:32 UTC, marcofranssen commented on charts/spire/charts/spire-server/values.yaml
> +      tag: latest-20230517
```suggestion
      tag: 5.2.15
```

2023-05-23 15:33 UTC, marcofranssen commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +      tag: latest-20230517
```suggestion
      tag: 5.2.15
```

2023-05-23 15:33 UTC, marcofranssen commented on charts/spire/charts/spiffe-oidc-discovery-provider/README.md
> +| tests.bash.image.tag | string | `"latest-20230517"` | Overrides the image tag |
```suggestion
| tests.bash.image.tag | string | `"5.2.15"` | Overrides the image tag |
```

2023-05-23 15:33 UTC, marcofranssen commented on charts/spire/README.md
> +| spiffe-oidc-discovery-provider.tests.bash.image.tag | string | `"latest-20230517"` | Overrides the image tag |
```suggestion
| spiffe-oidc-discovery-provider.tests.bash.image.tag | string | `"5.2.15"` | Overrides the image tag |
```

2023-05-23 15:34 UTC, marcofranssen commented on charts/spire/README.md
> +| tornjak-frontend.tests.bash.image.tag | string | `"latest-20230517"` | Overrides the image tag |
```suggestion
| tornjak-frontend.tests.bash.image.tag | string | `"5.2.15"` | Overrides the image tag |
```

2023-05-23 15:35 UTC, marcofranssen requested changes
Some inline suggestions to pin to the semver version of the image. Do we need a `global.tests.bash` to align with the pattern as well?

2023-05-23 15:49 UTC, kfox1111 commented
> Some inline suggestions to pin to the semver version of the image. Do we need a `global.tests.bash` to align with the pattern as well?

The other images don't have overrides at that level either. Just global.spire.image.registry to set them all at once to a mirror server, which should work here too.

2023-05-23 17:30 UTC, mrsabath commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +      # -- The OCI registry to pull the image from
```suggestion
      # -- The OCI registry to pull the tests image from
```

2023-05-23 17:31 UTC, mrsabath approved these changes
LGTM!

2023-05-23 17:31 UTC, mrsabath commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +      # -- The image pull policy
```suggestion
      # -- The tests image pull policy
```

2023-05-31 07:17 UTC, marcofranssen requested changes
Not sure if this makes it better. This is more then just a simple default we discussed yesterday. This is a lot of boilerplating and code to maintain. In that case I would prefer to just add it to the values.yaml.

2023-06-14 07:16 UTC, marcofranssen commented
I suggest we move all back to the valuews.yaml and use the approach from this PR https://github.com/spiffe/helm-charts/pull/311 to exclude them from docs.

2023-06-14 15:40 UTC, kfox1111 commented
Rolled back.

2023-06-14 19:17 UTC, marcofranssen approved these changes
LGTM

2023-06-14 19:17 UTC, merged