Add support for Tornjak components
spiffe/helm-charts pull request #234
Opened 2023-04-24 14:40 UTC by mrsabath

This PR integrates support for Tornjak components: API (backend) and UI (frontend). 
Tornjak provides an easy and intuitive graphical user interface and control plane for SPIRE.

2023-04-25 20:11 UTC, marcofranssen commented
I think I saw it somewhere in the labels or something. Will double check.

2023-05-01 20:44 UTC, kfox1111 commented on charts/spire/charts/spire-server/templates/_helpers.tpl
> +{{- end }}
This a dead macro? Just noticed it.

2023-05-01 20:44 UTC, kfox1111 commented on charts/spire/charts/spire-server/templates/_helpers.tpl
> +{{- end }}
This one too.

2023-05-12 07:28 UTC, marcofranssen requested changes
Found a couple small indentation issues which where resolved recently in other assets as well. See the suggestions. From the files tab you can bundle those in a single commit.

Also small suggestion on the NOTES to have a grammatically better sentence.

2023-05-12 07:28 UTC, marcofranssen commented on charts/spire/charts/spire-server/templates/NOTES.txt
> +testing only. Please do not use this version in production.
```suggestion
There is no authentication configured on Tornjak. Intended for testing
purposes only, do NOT use in production.
```

2023-05-12 07:28 UTC, marcofranssen commented on charts/spire/charts/spire-server/templates/tests/test-tornjak-connection.yaml
> +    - name: wget-tornjak-backend
```suggestion
    - name: curl-tornjak-backend
```

2023-05-12 07:28 UTC, marcofranssen commented on charts/spire/charts/spire-server/templates/tornjak-config.yaml
> +    {{- end }}
```suggestion
{{- end }}
```

2023-05-12 07:28 UTC, marcofranssen commented on charts/spire/charts/tornjak-frontend/templates/NOTES.txt
> +testing only. Please do not use this version in production.
```suggestion
There is no authentication configured on Tornjak. Intended for testing
purposes only, do NOT use in production.
```

2023-05-12 07:28 UTC, marcofranssen commented on charts/spire/charts/tornjak-frontend/templates/service.yaml
> +    {{- toYaml . | nindent 8 }}
```suggestion
    {{- toYaml . | nindent 4 }}
```

2023-05-12 09:06 UTC, marcofranssen commented
Testing from this branch I found following:

<img width="1253" alt="image" src="https://github.com/spiffe/helm-charts/assets/694733/77c59e38-da64-4254-ad6b-941e09be946e">

I have applied using the `examples/tornjak/values.yaml`

Then I ran `kubectl -n spire-system port-forward service/spire-tornjak-frontend 3000:3000`

Looking at the logs I see:

## Frontend

```
> tornjak-frontend@0.1.0 start
> PORT=$PORT_FE react-scripts start --openssl-legacy-provider

ℹ ｢wds｣: Project is running at http://10.2.10.84/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /usr/src/app/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Compiled successfully!
```

## Backend

```
-c /run/spire/config/server.conf -t /run/spire/tornjak-config/server.conf
/run/spire/config/server.conf
/run/spire/tornjak-config/server.conf
Starting to listen on :10000...
{map[DataStore:[sql] KeyManager:[disk] NodeAttestor:[k8s_psat] Notifier:[k8sbundle]] eu-west-1-swat-ops.swat-prototyping.com Plugin Info
DataStore Plugin: sql
Data: "connection_string" = "/run/spire/data/datastore.sqlite3"

"database_type" = "sqlite3"

KeyManager Plugin: disk
Data: "keys_path" = "/run/spire/data/keys.json"
```

2023-05-12 09:38 UTC, marcofranssen commented
Made a fix for previous comment here #276

2023-05-15 01:48 UTC, faisal-memon commented
Is it possible to deploy tornjak as a separate statefulset? If so, this would be a good one to break out into a subchart.

2023-05-15 05:09 UTC, faisal-memon commented on charts/spire/charts/spire-server/README.md
> +| tornjak.service.type | string | `"ClusterIP"` |  |
What do you think of naming this `tornjak-backend` to match the `tornjak-frontend`?

2023-05-15 09:41 UTC, marcofranssen commented
> Is it possible to deploy tornjak as a separate statefulset? If so, this would be a good one to break out into a subchart.

Tornjak requires just like the controller manager access to the spire-server socket and can therefore not run in another pod.

2023-05-16 17:53 UTC, merged

2023-05-16 18:06 UTC, kfox1111 reviewed
Some issues still to resolve.

2023-05-16 18:06 UTC, kfox1111 commented on charts/spire/charts/spire-server/templates/tornjak-config.yaml
> +      metadata = "insert metadata"
Is this something that should be configurable? Not sure what it is.

2023-05-16 18:06 UTC, kfox1111 commented on charts/spire/charts/tornjak-frontend/templates/_helpers.tpl
> +{{- define "tornjak-frontend.cluster-domain" -}}
This is now a spire-lib macro. It can be removed here and used directly in the rest of the template

2023-05-16 18:06 UTC, kfox1111 commented on charts/spire/charts/tornjak-frontend/templates/tests/test-tornjak-connection.yaml
> +      args: ['-k', '-s', '-f', 'http://{{ include "tornjak-frontend.fullname" . }}.{{ include "tornjak-frontend.namespace" . }}.svc.{{ include "tornjak-frontend.cluster-domain" . }}:{{ .Values.servic
Should use spire-lib.cluster-domain here.

2023-05-17 18:27 UTC, marcofranssen commented on charts/spire/README.md
> +| spire-server.tornjak.enabled | bool | `false` | Deploys Tornjak API (backend) |
It is there further down below as it is a separate chart.