Bump spire Helm Chart version from 0.9.1 to 0.10.0
spiffe/helm-charts pull request #371
Opened 2023-06-27 10:54 UTC by marcofranssen

Please review the below changelog to ensure this matches up with the semantic version being applied.

> **Note**: **Maintainers** ensure to run following after merging this PR to trigger the release workflow:
>
> ```shell
> git checkout main
> git pull
> git checkout release
> git pull
> git merge main
> git push
> ```

**Changes in this release**

* f4c421af Ensure the released OCI artifact is also captured in rekor
* 386e736e Bump sigstore/cosign-installer from 3.0.5 to 3.1.0 (#368)
* 99e01c67 Bump spire-controller-manager from 0.2.2 to 0.2.3 (#367)
* 3b666601 add missing federatesWith option (#361)

2023-06-27 15:40 UTC, faisal-memon approved these changes

2023-06-27 16:10 UTC, edwbuck requested changes
Where is the changelog?

2023-06-28 07:26 UTC, marcofranssen commented
@edwbuck see the description of this PR. Once released the changelog will end up in the releases tab in GitHub.

@kfox1111 because it is a new feature.

2023-06-28 15:39 UTC, kfox1111 approved these changes

2023-06-28 17:01 UTC, edwbuck approved these changes
Change logs probably should be a regular point in each release.

2023-06-28 17:01 UTC, merged