Add a FAQ and switch rare issue from README to it
spiffe/helm-charts pull request #437
Opened 2023-08-08 22:11 UTC by kfox1111

fixes https://github.com/spiffe/helm-charts/issues/433

2023-08-09 14:47 UTC, marcofranssen commented on FAQ.md
> +If you uninstall the spiffe csi driver manually before removing the chart, pods can still be using the driver an are unable to mount the csi volume.
```suggestion
If you uninstall the spiffe csi driver manually before removing the chart, pods can still be using the driver an are unable to unmount the csi volume.
```

2023-08-09 14:48 UTC, marcofranssen commented on FAQ.md
> +> **Note** This is enabled by default with newer versions as shown by the existence of:
```suggestion
> **Note**: This is enabled by default with newer versions as shown by the existence of:
```

2023-08-09 14:49 UTC, marcofranssen commented on charts/spire/README.md
```suggestion

## FAQ

For any issues see our [FAQ](../../FAQ.md)…
```

2023-08-09 14:49 UTC, marcofranssen commented on charts/spire/README.md.gotmpl
```suggestion

## FAQ
For any issues see our [FAQ](../../FAQ.md)…
```

2023-08-09 14:50 UTC, marcofranssen requested changes
Nice start on documenting these things. Few inline suggestions

2023-08-09 21:02 UTC, kfox1111 commented
Added a faq entry for https://github.com/spiffe/helm-charts/issues/440

2023-08-10 06:53 UTC, marcofranssen commented on charts/spire/README.md
> +For any issues see our [FAQ](../../FAQ.md)…
```suggestion
For any issues see our [FAQ](../../FAQ.md)…

```

Sorry, my suggestion missed the whiteline 😊

2023-08-10 06:54 UTC, marcofranssen commented on charts/spire/README.md.gotmpl
> +For any issues see our [FAQ](../../FAQ.md)…
```suggestion
For any issues see our [FAQ](../../FAQ.md)…

```

Sorry, my suggestion missed the whiteline 😊

2023-08-14 21:18 UTC, faisal-memon commented on FAQ.md
> +The chart requires `Projected Service Account Tokens` which has to be enabled on your k8s api server. In most cases this is already done for you.
```suggestion
The chart requires `Projected Service Account Tokens` which has to be enabled on your Kubernetes API server. In most cases this is already done for you.
```

2023-08-14 21:20 UTC, faisal-memon commented on FAQ.md
> +If you uninstall the spire chart before all users of the csi driver are removed, pods will get stuck in a terminating state waiting for the driver, that no longer is installed, to unmount the volumes
```suggestion
If you uninstall the SPIRE chart before all users of the CSI driver are removed, Pods will get stuck in a terminating state waiting for the driver, that no longer is installed, to unmount the volumes for the Pod. In order to fix this, reinstall the chart and remove all affected workloads that are not part of the SPIRE helm chart itself, before attempting to remove SPIRE again.
```

2023-08-14 21:20 UTC, faisal-memon commented on FAQ.md
> +If you uninstall the spiffe csi driver manually before removing the chart, pods can still be using the driver an are unable to unmount the csi volume.
```suggestion
If you uninstall the SPIFFE CSI driver manually before removing the chart, Pods can still be using the driver and are unable to unmount the csi volume.
```

2023-08-14 21:22 UTC, faisal-memon commented on FAQ.md
> +You can discover pods that use the driver with the following command:
```suggestion
You can discover Pods that use the driver with the following command:
```

2023-08-14 21:22 UTC, faisal-memon commented on FAQ.md
> +If you uninstall the SPIFFE CSI driver manually before removing the chart, Pods can still be using the driver and are unable to unmount the csi volume.
```suggestion
If you uninstall the SPIFFE CSI driver manually before removing the chart, Pods can still be using the driver and are unable to unmount the CSI volume.
```

2023-08-14 22:07 UTC, faisal-memon approved these changes
Thanks @kfox1111 creating this useful FAQ.

2023-08-15 16:41 UTC, marcofranssen approved these changes
LGTM

2023-08-15 16:42 UTC, merged