fix some issues found with kube-score
spiffe/helm-charts pull request #441
Opened 2023-08-10 15:12 UTC by drewwells

Statefulsets are supposed to have headless services assigned to them, see https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

The others changes are probably easier to see why kube-score complains

2023-08-10 15:54 UTC, drewwells commented
Seems like headless service is causing an issue with the test. I haven't been able to reproduce yet
```
 Args:
      -t
      30
      -h
      spire-eltibqgbgf-server.spire-eltibqgbgf
      -p
      8081
    State:          Running
      Started:      Thu, 10 Aug 2023 15:28:21 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lcgtz (ro)
```

2023-08-10 16:02 UTC, kfox1111 commented
I asked the api folks a while ago about required headless service and they said it really was optional but couldn't change it to such without breaking compatibility. It doesn't enforce it and a lot of folks never use it. So its extremely unlikely to ever break in the future.

2023-08-10 16:07 UTC, drewwells commented
> I asked the api folks a while ago about required headless service and they said it really was optional but couldn't change it to such without breaking compatibility. It doesn't enforce it and a lot of folks never use it. So its extremely unlikely to ever break in the future.

Do you have a link to that in documentation? I can push that up to kube-score and maybe this PR will pass without serviceName change

2023-08-10 16:11 UTC, kfox1111 commented
https://github.com/kubernetes/kubernetes/issues/69608

2023-08-22 18:16 UTC, marcofranssen requested changes
Few inline questions and suggestions.

2023-08-22 18:16 UTC, marcofranssen commented on charts/spire/charts/spire-server/templates/post-upgrade-hook.yaml
> +    {{- with .Values.podAnnotations }}
I wonder if these annotations need to be separately configurable from the workload itself? 🤔 

Not completely sure though.

2023-08-22 18:16 UTC, marcofranssen commented on charts/spire/charts/spire-server/templates/statefulset.yaml
> +          {{- with .Values.tools.kubectl.image.securityContext }}
```suggestion
          {{- with .Values.tools.kubectl.securityContext }}
```

should be one level up.

2023-08-22 18:16 UTC, marcofranssen commented on charts/spire/charts/spire-server/values.yaml
> +jobAnnotations: {}
From a practical point of view. 

- When will we use this?
- Do we need to be able to annotate differently per job?
- If so do we need post-upgrade-job annotations and pre-delete job annotations etc?

This is an open question, no thought or ideas on that myself. Trying to ensure we aren't adding things that need changes soon again, so we can keep the API stable.

2023-08-25 23:49 UTC, faisal-memon commented
@drewwells What do you think of putting the headless service behind a flag? Seems like not everyone will need it.

2023-08-27 14:04 UTC, marcofranssen commented
In that case just deploy it. No need for more flags

2023-08-27 16:54 UTC, closed without merging