Add support for oidc-discovery-provider ingress
spiffe/helm-charts pull request #60
Opened 2023-02-28 03:02 UTC by kfox1111

This patch enables exposing the oidc server out with an ingress along with tests to ensure it works.

Resolves #56

2023-03-01 10:28 UTC, marcofranssen requested changes
Couple of suggestions. will later today test it as well in my cluster to get a better feel on the UX of these new configurables.

2023-03-01 13:29 UTC, kfox1111 commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +  annotations: {}
its customary not to put in any annotations especially ones specific to any one ingress controller.

This config is straight out of helm create

2023-03-01 13:31 UTC, kfox1111 commented on charts/spire/charts/spiffe-oidc-discovery-provider/templates/ingress.yaml
> +            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
Ok. I can pull that out. It was generated by helm create  standard. But, yeah. if we're requiring at least 1.21, I can remove it.

2023-03-01 14:08 UTC, dennisgove commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +  annotations: {}
I agree about avoiding things specific to one ingress controller. Perhaps we could include in the example docs how one can set those annotations. That way we don't default any specific set in but do make it slightly easier for someone looking to set them.

2023-03-01 15:06 UTC, kfox1111 commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +  annotations: {}
+1. Where should that go?

2023-03-01 15:07 UTC, marcofranssen commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +  annotations: {}
Looking at a security best practice considering we had huge discussions in the past on the spire-oidc component it always has to run on https I think we can't avoid this. @evan2645 @azdagron

2023-03-01 15:09 UTC, marcofranssen commented on charts/spire/charts/spiffe-oidc-discovery-provider/templates/ingress.yaml
> +            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
https://github.com/spiffe/helm-charts#dependencies-and-version-compatibility

we even only officialy support last 3 versions, basically same as Amazon does for EKS.

Unofficially we agreed in an earlier meeting if it doesn't cause additional maintenance we can support further back. In this case it does take additional logic for older versions, so I think we can remove that here.

2023-03-01 15:11 UTC, kfox1111 commented on charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml
> +  annotations: {}
I believe tls redirect is default in ingress-nginx? At least when you have a tls cert specified in the ingress.

There is no standard for forcing ssl in ingress though. so would have to find all the ways the various ingress controllers do it.

Also, there is no sensitive material in the oidc discovery agent. its just the public keys and endpoints.

2023-03-16 15:33 UTC, kfox1111 commented on charts/spire/charts/spiffe-oidc-discovery-provider/templates/ingress.yaml
> +  name: {{ $fullName }}
now that namespaceOverride has merged, we need one here.

2023-03-16 17:59 UTC, marcofranssen approved these changes
LGTM :rocket:

2023-03-16 17:59 UTC, merged